import {cameras,modules,interpret,evaluate,compatible} from './rules.js';
const $=id=>document.getElementById(id);
const icons={play:'<path d="m7 4 13 8-13 8z"/>',pause:'<path d="M8 4v16M16 4v16"/>',restart:'<path d="M3 10a9 9 0 1 1 1 8M3 4v6h6"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',evidence:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h3"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=t=>`${Math.floor((t||0)/60)}:${String(Math.floor((t||0)%60)).padStart(2,'0')}`;
const video=$('mainVideo');let selected=cameras[0],reference=false,suggestion=null,showOverlay=true,events=[],noticeTimer;
let rules={};try{const saved=JSON.parse(localStorage.getItem('replay-rules')||'{}');for(const c of cameras){const r=saved[c.id];if(r&&compatible(c,r)&&Number.isFinite(r.threshold)&&r.threshold>=.1&&r.threshold<=60)rules[c.id]=r;}}catch{}
function persist(){try{localStorage.setItem('replay-rules',JSON.stringify(rules));}catch{notify('Browser storage unavailable. Rules will last for this session.');}}
function notify(message){$('notification').textContent=message;$('notification').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notification').hidden=true,3500);}
function cameraGrid(){ $('cameraGrid').innerHTML=cameras.map((c,i)=>`<button class="camera-card ${c.id===selected.id?'selected':''}" data-camera="${c.id}" aria-pressed="${c.id===selected.id}"><img src="demo-footage/previews/${c.file}_1.jpg" alt="${c.name} CCTV preview"><span class="cam-tag">CAM 0${i+1}</span>${c.id===selected.id?'<span class="check">✓</span>':''}<strong>${c.name}</strong><small>${rules[c.id]?'1 module attached':'No modules attached'}</small></button>`).join('');document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>selectCamera(b.dataset.camera));}
function selectCamera(id,ref=false){selected=cameras.find(c=>c.id===id)||cameras[0];reference=ref;video.pause();video.src=`demo-footage/factory-cctv/${reference?selected.reference:selected.file}.mp4`;video.poster=`demo-footage/previews/${reference?selected.reference:selected.file}_1.jpg`;video.load();$('videoError').hidden=true;$('viewerName').textContent=selected.name;$('viewerLocation').textContent=selected.location;$('scenarioButton').classList.toggle('selected',!reference);$('referenceButton').classList.toggle('selected',reference);$('scenarioButton').setAttribute('aria-pressed',String(!reference));$('referenceButton').setAttribute('aria-pressed',String(reference));cameraGrid();attached();renderSuggestion();tick();}
function attached(){const rule=rules[selected.id];$('attachedCount').textContent=rule?'1':'0';$('attached').innerHTML=rule?`<div class="attached-card"><strong>✓ ${modules[rule.module].name}</strong><small>Threshold: ${rule.threshold}s · Demo annotations</small><button id="removeModule" class="text-button">Remove module</button></div>`:'<div class="no-module">No modules yet. Start with a requirement above.</div>';$('analysisBadge').textContent=rule?'DEMO ANNOTATIONS':'No module attached';if(rule)$('removeModule').onclick=()=>{delete rules[selected.id];events=events.filter(e=>e.camera!==selected.id);persist();attached();cameraGrid();renderEvidence();tick();notify('Module removed from this camera');};}
function renderSuggestion(){const host=$('suggestion');if(!suggestion){host.innerHTML='';return;}if(suggestion.error){host.innerHTML=`<div class="inline-error">${esc(suggestion.error)}</div>`;return;}const m=modules[suggestion.module];const match=compatible(selected,suggestion);const target=cameras.find(c=>c.module===suggestion.module);host.innerHTML=`<div class="suggestion-card"><div class="eyebrow">MATCHED MODULE · LOCAL DEMO</div><h3>${m.name}</h3><p>${m.description}</p><label class="threshold">Duration threshold <span><input id="threshold" type="number" min="0.1" max="60" step="0.1" value="${suggestion.threshold}" aria-label="Duration threshold in seconds"> s</span></label>${!match?`<p>This example is available on <strong>${target.name}</strong>.</p>`:''}<button class="button primary" id="attachModule">${match?'Attach to this camera':'Switch camera & attach'} <span>+</span></button></div>`;$('threshold').oninput=e=>suggestion.threshold=Number(e.target.value);$('attachModule').onclick=()=>{if(!Number.isFinite(suggestion.threshold)||suggestion.threshold<.1||suggestion.threshold>60){notify('Enter a duration between 0.1 and 60 seconds.');return;}const id=match?selected.id:target.id;rules[id]={...suggestion};events=events.filter(e=>e.camera!==id);persist();suggestion=null;selectCamera(id);renderEvidence();notify(`${m.name} attached. Play the clip to preview.`);};}
function submit(text){suggestion=interpret(text);renderSuggestion();}
$('ruleForm').onsubmit=e=>{e.preventDefault();submit($('requirement').value);};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('requirement').value=b.dataset.prompt;submit(b.dataset.prompt);});
function renderOverlay(event){const rule=rules[selected.id];const svg=$('overlay');svg.innerHTML='';if(!rule||!showOverlay)return;if(rule.module==='zone')svg.innerHTML='<polygon points="713,13 741,13 1000,562 934,562" fill="#87d6a220" stroke="#a9e8ba" stroke-width="2" stroke-dasharray="8 5"/><rect x="700" y="66" width="197" height="27" rx="4" fill="#1c423add"/><text x="710" y="84" font-size="12" font-family="sans-serif" fill="#e5ffe8">Illustrative walkway region</text>';if(event&&rule.module!=='zone')svg.innerHTML='<rect x="16" y="60" width="212" height="29" rx="5" fill="#1c3028cc"/><text x="27" y="79" font-size="12" font-family="sans-serif" fill="#f1dcb4">Source-label preview · verify visually</text>';}
function tick(){const duration=Number.isFinite(video.duration)?video.duration:selected.duration;const time=video.currentTime||0;$('timeLabel').textContent=`${format(time)} / ${format(duration)}`;$('seek').value=String(duration?time/duration*1000:0);const rule=rules[selected.id];const event=evaluate(selected,rule,time,reference);$('eventToast').hidden=!event;if(event){$('eventTitle').textContent=event.title;const key=`${selected.id}:${rule.threshold}`;if(!events.some(e=>e.key===key)){events.unshift({...event,key,camera:selected.id,cameraName:selected.name,file:selected.file,threshold:rule.threshold});renderEvidence();}}renderOverlay(event);$('viewerStatus').textContent=rule?(reference?'Reference example · no authored event':event?'Demo event active · click evidence to review':time>selected.event.end?'Replay complete · review the evidence below':'Demo module ready · play to preview'):'Select a module to start a demo preview';}
function renderEvidence(){$('eventCount').textContent=String(events.length);$('evidenceList').innerHTML=events.length?events.map((e,i)=>`<button class="evidence-row" data-evidence="${i}"><img src="demo-footage/previews/${e.file}_1.jpg" alt="Event preview"><span><strong>${e.title}</strong><small>${e.cameraName} · ${format(e.trigger)} · Authored example</small></span><span class="arrow">↗</span></button>`).join(''):'<div class="empty-evidence">◇<strong>Your evidence will appear here</strong>Attach a module and play a scenario to preview an event.</div>';document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{const e=events[Number(b.dataset.evidence)];selectCamera(e.camera);const seek=()=>{video.currentTime=e.trigger;tick();};if(video.readyState>=1)seek();else video.addEventListener('loadedmetadata',seek,{once:true});notify(e.detail);$('mainVideo').scrollIntoView({behavior:'smooth',block:'center'});});}
async function play(){try{if(video.paused){if(video.ended)video.currentTime=0;await video.play();}else video.pause();}catch{notify('Playback failed. Check that the video file is available.');}}
$('playButton').onclick=play;video.onclick=play;video.ontimeupdate=tick;video.onloadedmetadata=tick;video.onplay=()=>{$('playButton').innerHTML=icon('pause');$('playButton').setAttribute('aria-label','Pause footage');};video.onpause=()=>{$('playButton').innerHTML=icon('play');$('playButton').setAttribute('aria-label','Play footage');};video.onerror=()=>{$('videoError').hidden=false;};$('seek').oninput=e=>{if(Number.isFinite(video.duration))video.currentTime=Number(e.target.value)/1000*video.duration;tick();};$('restartButton').onclick=()=>{video.currentTime=0;tick();};$('speedButton').onclick=()=>{const rates=[1,1.5,2,.5];video.playbackRate=rates[(rates.indexOf(video.playbackRate)+1)%rates.length];$('speedButton').textContent=`${video.playbackRate}×`;};$('scenarioButton').onclick=()=>selectCamera(selected.id,false);$('referenceButton').onclick=()=>selectCamera(selected.id,true);$('overlayToggle').onclick=()=>{showOverlay=!showOverlay;$('overlayToggle').textContent=`Overlay ${showOverlay?'on':'off'}`;$('overlayToggle').setAttribute('aria-pressed',String(showOverlay));tick();};$('clearEvidence').onclick=()=>{events=[];renderEvidence();notify('Evidence cleared');};$('resetButton').onclick=()=>{rules={};events=[];suggestion=null;$('requirement').value='';persist();selectCamera(cameras[0].id);renderEvidence();notify('Workspace reset');};$('aboutButton').onclick=()=>$('aboutDialog').showModal();$('closeAbout').onclick=()=>$('aboutDialog').close();$('evidenceNav').onclick=()=>$('evidenceSection').scrollIntoView({behavior:'smooth'});$('workspaceNav').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('workspaceNav').innerHTML=icon('grid');$('evidenceNav').innerHTML=icon('evidence');$('playButton').innerHTML=icon('play');$('restartButton').innerHTML=icon('restart');selectCamera(selected.id);renderEvidence();
