"""Build the regulations tables from data/regulations.json.

The JSON file is the single source of truth. Never edit the markdown by hand.
Each row has a `settings` list. The general table shows every row.
The by-setting view filters the same rows, for example for a chem lab.

Run:    uv run scripts/build_regulations_table.py                 (write both files)
Check:  uv run scripts/build_regulations_table.py --check         (fail if out of date)
Filter: uv run scripts/build_regulations_table.py --setting chem-lab   (print one view)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "regulations.json"
ALL_DOC_PATH = ROOT / "docs" / "regulations-table.md"
SETTING_DOC_PATH = ROOT / "docs" / "regulations-by-setting.md"

PACK_TITLES = {
    "OSHA": "OSHA general industry: 29 CFR Part 1910",
    "OSHA-CONST": "OSHA construction: 29 CFR Part 1926",
    "cGMP": "cGMP: 21 CFR Part 211",
    "EPA": "EPA hazardous waste: 40 CFR Part 262",
    "ISO": "ISO: 45001 and 14644",
}

ALL_INTRO = """\
# Regulations table

This table lists specific clauses that the Video Compliance Agent can check.
Each row has the requirement and the cue that a camera can show.
Use it to write rule packs and ingestion prompts.
See [the project description](261009-video-agents-hackathon-project-description.md) for the overview.

The data is in [data/regulations.json](../data/regulations.json).
Do not edit this file by hand. Edit the JSON and run `uv run scripts/build_regulations_table.py`.
"""

HOW_TO_READ = """\
## How to read this table

- **Clause:** the paragraph to cite in a finding.
- **Settings:** where the rule applies. See the table of settings below.
  The general view is this whole table. For one setting, see [the by-setting view](regulations-by-setting.md).
- **Requirement:** the rule in plain words. It is a summary, not the legal text.
- **Violation cue:** an example of what the camera can see when the rule is broken.
  The cue is a detection idea. It is not part of the regulation.
- Read the full clause before you cite it in a report.
"""

SETTING_INTRO = """\
# Regulations by setting

Each section lists the rules that apply in one setting.
A rule that applies in more than one setting is in more than one section.
For the full table, see [the regulations table](regulations-table.md).

The data is in [data/regulations.json](../data/regulations.json).
Do not edit this file by hand. Edit the JSON and run `uv run scripts/build_regulations_table.py`.
"""


def escape_cell(text):
    return text.replace("|", "\\|").replace("\n", " ")


def render_line(cells):
    return "| " + " | ".join(escape_cell(c) for c in cells) + " |"


def row_cells(row, labels=None, show_standard=False):
    cells = [row["clause"], row["topic"], row["requirement"], row["cue"]]
    if labels is not None:
        cells.insert(2, ", ".join(labels[s] for s in row["settings"]))
    if show_standard:
        cells.insert(0, row["standard"])
    return cells


def header_cells(labels=None, show_standard=False):
    cells = ["Clause", "Topic", "Requirement", "Violation cue"]
    if labels is not None:
        cells.insert(2, "Settings")
    if show_standard:
        cells.insert(0, "Standard")
    return cells


def render_table(rows, labels=None, show_standard=False):
    header = header_cells(labels, show_standard)
    lines = [render_line(header), "|" + "---|" * len(header)]
    lines += [render_line(row_cells(r, labels, show_standard)) for r in rows]
    return "\n".join(lines)


def group_by_pack(rows):
    groups = {}
    for row in rows:
        groups.setdefault(row["pack"], []).append(row)
    return groups


def filter_by_setting(rows, setting, known=None):
    if known is not None and setting not in known:
        raise ValueError(f"unknown setting: {setting}. Known: {', '.join(sorted(known))}")
    return [r for r in rows if setting in r["settings"]]


def render_pack_section(pack, rows, source, labels):
    title = PACK_TITLES[pack]
    return f"## {title}\n\nSource: {source}\n\n{render_table(rows, labels)}\n"


def render_settings_summary(data):
    lines = ["| Setting | What it covers | Rules |", "|---|---|---|"]
    for sid, info in data["settings"].items():
        count = len(filter_by_setting(data["rows"], sid))
        lines.append(render_line([info["label"], info["description"], str(count)]))
    return "## Settings\n\n" + "\n".join(lines) + "\n"


def render_not_visible(items):
    lines = ["| Clause | Topic | Why |", "|---|---|---|"]
    for item in items:
        cells = (f"{item['pack']} {item['clause']}", item["topic"], item["reason"])
        lines.append(render_line(cells))
    return (
        "## Not visible in video\n\n"
        "The app cannot check these clauses from video alone.\n"
        "Do not make rules for them.\n\n" + "\n".join(lines) + "\n"
    )


def render_summary(data):
    counts = group_by_pack(data["rows"])
    parts = ", ".join(f"{pack} {len(rows)}" for pack, rows in counts.items())
    return (
        f"The table has {len(data['rows'])} rules ({parts}).\n"
        f"Retrieved {data['retrieved']}. Source text: eCFR for the CFR packs.\n"
    )


def setting_labels(data):
    return {sid: info["label"] for sid, info in data["settings"].items()}


def render_document(data):
    labels = setting_labels(data)
    sections = [
        render_pack_section(pack, rows, data["sources"][pack], labels)
        for pack, rows in group_by_pack(data["rows"]).items()
    ]
    parts = [
        ALL_INTRO,
        render_summary(data),
        HOW_TO_READ,
        render_settings_summary(data),
        *sections,
        render_not_visible(data["not_visible"]),
    ]
    return "\n".join(parts)


def render_setting_section(sid, info, rows):
    return (
        f"## {info['label']} ({len(rows)} rules)\n\n"
        f"{info['description']}\n\n"
        f"{render_table(rows, show_standard=True)}\n"
    )


def render_setting_document(data):
    known = set(data["settings"])
    sections = [
        render_setting_section(sid, info, filter_by_setting(data["rows"], sid, known))
        for sid, info in data["settings"].items()
    ]
    return "\n".join([SETTING_INTRO, *sections])


def print_setting_view(data, setting):
    rows = filter_by_setting(data["rows"], setting, set(data["settings"]))
    print(render_table(rows, show_standard=True))


def check_files(data):
    expected = {
        ALL_DOC_PATH: render_document(data),
        SETTING_DOC_PATH: render_setting_document(data),
    }
    stale = [p for p, text in expected.items() if p.read_text() != text]
    for path in stale:
        print(f"{path} is out of date. Run this script without --check.")
    if not stale:
        print("Regulations tables are up to date.")
    return 1 if stale else 0


def write_files(data):
    ALL_DOC_PATH.write_text(render_document(data))
    SETTING_DOC_PATH.write_text(render_setting_document(data))
    print(f"Wrote {ALL_DOC_PATH.name} and {SETTING_DOC_PATH.name} ({len(data['rows'])} rules).")
    return 0


def main(argv):
    data = json.loads(DATA_PATH.read_text())
    if "--setting" in argv:
        try:
            print_setting_view(data, argv[argv.index("--setting") + 1])
        except ValueError as error:
            print(error, file=sys.stderr)
            return 2
        return 0
    if "--check" in argv:
        return check_files(data)
    return write_files(data)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
